Vamos calcular qual foi a maior queda em um ano da PRIO3 e sua maior ascensão

In [21]:
import pandas as pd
from pandas_datareader import data as pdr
import numpy as np
import yfinance as yf

In [22]:
cot = yf.download("PRIO3.SA", "2010-10-25", "2023-06-30")["Adj Close"]
cot

[*********************100%***********************]  1 of 1 completed

Date
2010-10-25    23.340000
2010-10-26    22.500000
2010-10-27    22.700001
2010-10-28    22.500000
2010-10-29    22.740000
                ...
2023-06-23    38.209999
2023-06-26    37.040001
2023-06-27    35.799999
2023-06-28    36.139999
2023-06-29    36.290001
Name: Adj Close, Length: 3147, dtype: float64

In [23]:
cotacoes_maxdd = cot.to_frame()
cotacoes_maxdd['ano'] = cotacoes_maxdd.index.year


cotacoes_maxdd['maxima_do_ano'] = cotacoes_maxdd.groupby("ano")["Adj Close"].cummax()

cotacoes_maxdd

            Adj Close   ano  maxima_do_ano
Date
2010-10-25  23.340000  2010          23.34
2010-10-26  22.500000  2010          23.34
2010-10-27  22.700001  2010          23.34
2010-10-28  22.500000  2010          23.34
2010-10-29  22.740000  2010          23.34
...               ...   ...            ...
2023-06-23  38.209999  2023          42.75
2023-06-26  37.040001  2023          42.75
2023-06-27  35.799999  2023          42.75
2023-06-28  36.139999  2023          42.75
2023-06-29  36.290001  2023          42.75

[3147 rows x 3 columns]

In [24]:
cotacoes_maxdd["Quedas"] = cotacoes_maxdd["Adj Close"]/cotacoes_maxdd["maxima_do_ano"] - 1

cotacoes_maxdd

            Adj Close   ano  maxima_do_ano    Quedas
Date
2010-10-25  23.340000  2010          23.34  0.000000
2010-10-26  22.500000  2010          23.34 -0.035990
2010-10-27  22.700001  2010          23.34 -0.027421
2010-10-28  22.500000  2010          23.34 -0.035990
2010-10-29  22.740000  2010          23.34 -0.025707
...               ...   ...            ...       ...
2023-06-23  38.209999  2023          42.75 -0.106199
2023-06-26  37.040001  2023          42.75 -0.133567
2023-06-27  35.799999  2023          42.75 -0.162573
2023-06-28  36.139999  2023          42.75 -0.154620
2023-06-29  36.290001  2023          42.75 -0.151111

[3147 rows x 4 columns]

In [25]:
cotacoes_maxdd.groupby("ano")["Quedas"].min()

ano
2010   -0.088484
2011   -0.757548
2012   -0.722539
2013   -0.883186
2014   -0.690345
2015   -0.721781
2016   -0.466527
2017   -0.274115
2018   -0.502053
2019   -0.295610
2020   -0.787910
2021   -0.321137
2022   -0.287256
2023   -0.299883
Name: Quedas, dtype: float64

In [ ]:
# Nessa Análise podemos perceber que o comprador que comprou mais no topo e vendeu mais na queda perdeu entre
# 8% a 78% a depender do ano

In [26]:
cotacoes_maxdd['Minima_do_ano'] = cotacoes_maxdd.groupby("ano")["Adj Close"].cummin()
cotacoes_maxdd

            Adj Close   ano  maxima_do_ano    Quedas  Minima_do_ano
Date
2010-10-25  23.340000  2010          23.34  0.000000          23.34
2010-10-26  22.500000  2010          23.34 -0.035990          22.50
2010-10-27  22.700001  2010          23.34 -0.027421          22.50
2010-10-28  22.500000  2010          23.34 -0.035990          22.50
2010-10-29  22.740000  2010          23.34 -0.025707          22.50
...               ...   ...            ...       ...            ...
2023-06-23  38.209999  2023          42.75 -0.106199          29.93
2023-06-26  37.040001  2023          42.75 -0.133567          29.93
2023-06-27  35.799999  2023          42.75 -0.162573          29.93
2023-06-28  36.139999  2023          42.75 -0.154620          29.93
2023-06-29  36.290001  2023          42.75 -0.151111          29.93

[3147 rows x 5 columns]

In [30]:
cotacoes_maxdd["Altas"] = cotacoes_maxdd["Adj Close"]/cotacoes_maxdd["Minima_do_ano"] -1

cotacoes_maxdd

            Adj Close   ano  maxima_do_ano    Quedas  Minima_do_ano     Altas
Date
2010-10-25  23.340000  2010          23.34  0.000000          23.34  0.000000
2010-10-26  22.500000  2010          23.34 -0.035990          22.50  0.000000
2010-10-27  22.700001  2010          23.34 -0.027421          22.50  0.008889
2010-10-28  22.500000  2010          23.34 -0.035990          22.50  0.000000
2010-10-29  22.740000  2010          23.34 -0.025707          22.50  0.010667
...               ...   ...            ...       ...            ...       ...
2023-06-23  38.209999  2023          42.75 -0.106199          29.93  0.276645
2023-06-26  37.040001  2023          42.75 -0.133567          29.93  0.237554
2023-06-27  35.799999  2023          42.75 -0.162573          29.93  0.196124
2023-06-28  36.139999  2023          42.75 -0.154620          29.93  0.207484
2023-06-29  36.290001  2023          42.75 -0.151111          29.93  0.212496

[3147 rows x 6 columns]

In [31]:
cotacoes_maxdd.groupby("ano")["Altas"].max()

ano
2010    0.483746
2011    0.392308
2012    0.806701
2013    0.439394
2014    1.301587
2015    1.199301
2016    2.463768
2017    2.510730
2018    1.410367
2019    2.315952
2020    5.781643
2021    1.057748
2022    1.082207
2023    0.292015
Name: Altas, dtype: float64

In [ ]:
# Tendo em vista esses dados, nós podemos perceber que o ano de 2020 um investidor
# comprando no melhor momento ele consegue gerar um resultado de até 5x o investido;